#!/usr/bin/env python3
#==============================================================================
#title           : profile_config.py
#description     : Profile config template file.
#author          : Arturo Plauchu (arturo.plauchu@gmail.com)
#date            : September 2017
#python_version  : 3 or later
#license         : GPL v2.0
#==============================================================================


#Template Strings
PROFILE_INFO = '\
#!/usr/bin/env python3\n\
#==============================================================================\n\
#title           : %s.py\n\
#description     : Profile file. It contains data collection with test\n\
#                  names and order of execution..\n\
#author          : Auto generated by PTest Framework Tools - version [%s]\n\
#date            : %s\n\
#python_version  : 3 or later\n\
#==============================================================================\n\
"""\n\
%s\n\
"""\n'
PROFILE_HEAD = '\n\
profile_def = {\n\
    \'type\' : \'profile\',\n\
    \'name\' : \'%s\',\n\
    \'descp\': \'%s\',\n\
    \'tests\' : {\n'
PROFILE_TEST = '        %s : { \'name\' : \'%s\', \'descp\' : \'%s\'},\n'
PROFILE_FOOT = '\
        }\n\
    }'
