#!/usr/bin/env python3
#==============================================================================
#title           : test_config.py
#description     : Test config template file.
#author          : Arturo Plauchu (arturo.plauchu@gmail.com)
#date            : September 2017
#python_version  : 3 or later
#license         : GPL v2.0
#==============================================================================


#==============================================================================
#=========================== TEST FILE TEMPLATE ===============================
#==============================================================================

#Template Strings
TESTFILE_INFO = '\
#!/usr/bin/env python3\n\
#==============================================================================\n\
#title           : %s.py\n\
#description     : Test file. It contains test cases as methods with\n\
#                  description as comments and a data collection with method\n\
#                  names, order of execution and mode.\n\
#author          : Auto generated by PTest Framework Tools - version [%s]\n\
#date            : %s\n\
#python_version  : 3 or later\n\
#==============================================================================\n\
"""\n\
%s\n\
"""\n\n'

TESTFILE_HEAD = '\
#==============================================================================\n\
#============================= FWK IMPORTS ====================================\n\
#==============================================================================\n\
\n\
from lib import sys_lib as SYS\n\
from lib import log_lib as LOG\n\
from lib import testctrl_lib as CTRL\n\
from src.tests.%s.testlib import %s_lib as testLIB\n\
from src.tests.%s.testconfig import %s_config as testCFG\n\
\n\
#==============================================================================\n\
#============================= OTHER IMPORTS ==================================\n\
#==============================================================================\n\
\n\
import sys\n\
\n\
#==============================================================================\n\
#============================ TEST DEFINITION =================================\n\
#==============================================================================\n\
\n\
#Test definition structure\n\
test_def = testLIB.test_def\n\
\n\
#Test Lib Class\n\
test = testLIB.%s()\n\
\n\
#==============================================================================\n\
#============================= TEST CASES =====================================\n\
#==============================================================================\n\n'

TESTFILE_TC = '\
@CTRL.TestCase\n\
def %s(args):\n\
    """\n\
    %s\n\
    """\n\
\n\
    log.logshow(\'[ %%s ]\' %% (args[1]), LOG.SUCCESS, LOG.OK)\n\
    return SYS.RC_NO_ERROR\n\
\n\
#==============================================================================\n'

TESTFILE_FOOT = '\
#================================ MAIN ========================================\n\
#==============================================================================\n\
\n\
if __name__ == "__main__":\n\
    log = LOG.Logging(sys.argv[5])\n\
    test.main(sys.argv, globals(), log)\n'



#==============================================================================
#============================ TEST LIB TEMPLATE ===============================
#==============================================================================

TESTLIBFILE_INFO = '\
#!/usr/bin/env python3\n\
#==============================================================================\n\
#title           : %s_lib.py\n\
#description     : Test lib file to create classes or methods for\n\
#                  control test execution.\n\
#author          : Auto generated by PTest Framework Tools - version [%s]\n\
#date            : %s\n\
#python_version  : 3 or later\n\
#==============================================================================\n\
"""\n\
%s\n\
"""\n\n'


TESTLIBFILE_HEAD = '\
#==============================================================================\n\
#============================= FWK IMPORTS ====================================\n\
#==============================================================================\n\
\n\
from lib import common_lib as LIB\n\
from lib import log_lib as LOG\n\
from lib import sys_lib as SYS\n\
from lib import testctrl_lib as CTRL\n\
from src.tests.%s.testconfig import %s_config as testCFG\n\
\n\
#==============================================================================\n\
#============================= OTHER IMPORTS ==================================\n\
#==============================================================================\n\
\n\
#...\n\n'

TESTLIBFILE_TESTDEF_1 = '\
#==============================================================================\n\
#============================ TEST DEFINITION =================================\n\
#==============================================================================\n\
\n\
test_def = {\n\
    \'type\' : \'test\',\n\
    \'name\' : \'%s\',\n\
    \'descp\' : \'%s\',\n\
    \'usermodes\' : {\n'

TESTLIBFILE_TESTDEF_2 = '\
        \'%s\' : %s,\n'

TESTLIBFILE_TESTDEF_3 = '\
    },\n\
    \'test_cases\' : {\n'

TESTLIBFILE_TESTDEF_4 = '\
        %s : { \'name\' : \'%s\',  \'descp\' : \'%s\',\n\
               \'mode\' : \'%s\', \'concurrency_inst\' : %s, \'protected\' : %s},\n'

TESTLIBFILE_TESTDEF_4_ARGS = '\
        %s : { \'name\' : \'%s\',  \'descp\' : \'%s\',\n\
               \'mode\' : \'%s\', \'concurrency_inst\' : %s, \'protected\' : %s, \'args\' : \'%s\'},\n'

TESTLIBFILE_TESTDEF_5 = '\
        }\n\
    }\n\n'

TESTLIBFILE_EXT = '\
#==============================================================================\n\
#=================================== VARS =====================================\n\
#==============================================================================\n\
\n\
#...\n\
\n\
#==============================================================================\n\
#================================ CLASSES =====================================\n\
#==============================================================================\n\
\n\
#This class takes a base of Control class that contains methods\n\
#to control test case execution to avoid mix control and test logic.\n\
class %s(CTRL.TestController):\n\
    """\n\
    Class to extend functionality of %s test.\n\
    """\n\
\n\
    def __init__(self):\n\
        """\n\
        Constructor\n\
        """\n\
\n\
        super().__init__(test_def)\n\
\n\
    #==========================================================================\n\
\n\
    def extraFunc(self, msg):\n\
        """\n\
        Example of functional extension\n\
\n\
        type: str\n\
        @param: msg - just a string message\n\
\n\
        rtype: number\n\
        @return: 0\n\
        """\n\
\n\
        self.log.logshow(testCFG.SW_1_MSG %% msg, LOG.INFO)\n\
        return 0\n\
\n'

#==============================================================================
#============================ TEST CONFIG TEMPLATE ============================
#==============================================================================

TESTCFGFILE_INFO = '\
#!/usr/bin/env python3\n\
#==============================================================================\n\
#title           : %s_config.py\n\
#description     : Test config file to define HW and SW variables\n\
#                  as constants.\n\
#author          : Auto generated by PTest Framework Tools - version [%s]\n\
#date            : %s\n\
#python_version  : 3 or later\n\
#==============================================================================\n\
"""\n\
%s\n\
"""\n\n'

TESTCFGFILE_HEAD = '\
#==============================================================================\n\
#=============================== CONFIG HW ====================================\n\
#==============================================================================\n\
\n\
HW_VTEST = \'HW constant from %s_config\'\n\
\n\
#==============================================================================\n\
#=============================== CONFIG SW ====================================\n\
#==============================================================================\n\
\n\
SW_VTEST = \'SW constant from %s_config\'\n\
\n\
#Messages\n\
SW_1_MSG = \'Msg from extrafunctionality: %%s\'\n'
